import { StyleSheet } from '@react-pdf/renderer';

export const pdfColors = {
  ink: '#0a0a0c',
  text: '#27272a',
  muted: '#71717a',
  border: '#d4d4d8',
  accent: '#06b6d4',
  bgSubtle: '#f4f4f5',
};

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 56,
    paddingBottom: 64,
    paddingHorizontal: 56,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: pdfColors.text,
    lineHeight: 1.5,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.border,
    borderBottomStyle: 'solid',
  },
  brandName: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.ink,
  },
  brandMeta: {
    fontSize: 8,
    color: pdfColors.muted,
    marginTop: 2,
  },
  docTitle: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.ink,
    marginBottom: 12,
  },
  h1: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.ink,
    marginTop: 14,
    marginBottom: 6,
  },
  h2: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.ink,
    marginTop: 10,
    marginBottom: 4,
  },
  h3: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.ink,
    marginTop: 8,
    marginBottom: 3,
  },
  paragraph: {
    marginBottom: 6,
  },
  listItem: {
    flexDirection: 'row',
    marginBottom: 3,
    paddingLeft: 10,
  },
  bullet: {
    width: 12,
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 56,
    right: 56,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 8,
    color: pdfColors.muted,
    borderTopWidth: 1,
    borderTopColor: pdfColors.border,
    borderTopStyle: 'solid',
    paddingTop: 6,
  },
  receipt: {
    marginTop: 24,
    padding: 12,
    backgroundColor: pdfColors.bgSubtle,
    borderRadius: 4,
  },
  receiptHeading: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.ink,
    marginBottom: 6,
  },
  receiptRow: {
    flexDirection: 'row',
    marginBottom: 2,
  },
  receiptLabel: {
    width: 90,
    color: pdfColors.muted,
    fontSize: 8,
  },
  receiptValue: {
    flex: 1,
    fontSize: 8,
    color: pdfColors.text,
  },
  table: {
    marginTop: 8,
    marginBottom: 12,
    borderTopWidth: 1,
    borderTopColor: pdfColors.border,
    borderTopStyle: 'solid',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.border,
    borderBottomStyle: 'solid',
    paddingVertical: 6,
  },
  tableCellDesc: {
    flex: 3,
    paddingRight: 8,
  },
  tableCellNum: {
    flex: 1,
    textAlign: 'right',
  },
  tableHeader: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: pdfColors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  totalsBlock: {
    marginTop: 8,
    alignSelf: 'flex-end',
    width: 220,
  },
  totalsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 3,
  },
  totalsRowEmphasis: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: pdfColors.ink,
    borderTopStyle: 'solid',
    fontFamily: 'Helvetica-Bold',
  },
});
